image: node:18

stages:
  - install
  - test
  - lint
  - build

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  script:
    - npm install

run_tests:
  stage: test
  script:
    - echo "No tests defined. Skipping..."  # Optional: add test framework later
  allow_failure: true

lint_check:
  stage: lint
  script:
    - npx eslint . || echo "No ESLint configured"  # Optional: remove if not using

build_check:
  stage: build
  script:
    - node -v
    - node app.js &
    - sleep 5
    - curl http://localhost:3000 || echo "Server failed to start (this is a dummy check)"
  allow_failure: true
